project:
  type: website
  output-dir: docs
  resources:
    - "content/images/**"
  
website:
  page-navigation: true
  title: "Prediction-Based Inference Short Course"
  description: "Short-course materials for Prediction-Based Inference: Methods & Applications"
  site-url: "https://thmccormick.github.io/ipd-short-course/"

  repo-url: https://github.com/thmccormick/ipd-short-course
  repo-actions: [edit, issue]
  
  open-graph: true
  
  page-footer:
    right: "Proudly built with [OTTR](https://www.ottrproject.org/) and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2026, Tyler H. McCormick"
    background: "#F4F4F4"
  
  sidebar:
    #background: "#f4f4f4"
    logo: "content/images/ipd.png"
    pinned: true
    align: center
    tools:
      - icon: moon
        href: javascript:window.quartoToggleColorScheme();
        text: "Toggle Dark Mode"
      - icon: github
        href: https://github.com/ipd-tools
        text: "GitHub Organization"
      - icon: code-square
        href: https://github.com/thmccormick/ipd-short-course
        text: "Source Code"
      - icon: person-fill
        text: "Presenter"
        menu:
          - text: Tyler H. McCormick
            url: https://thmccormick.github.io/
          
    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - text: "Home"
        href: index.qmd
      - text: "Overview"
        href: content/slides.qmd
      - section: "Resources"
        contents:
          - text: "Setup & Prerequisites"
            href: content/setup.qmd
          - text: "Additional Information"
            href: content/information.qmd
      - section: "Modules"
        contents:
          - text: "Getting Started"
            href: content/Unit00_GettingStarted.qmd
          - text: "Measuring Adiposity"
            href: content/Unit02_MeasuringAdiposity.qmd
          - text: "Proteomics with AlphaFold"
            href: content/Unit01_AlphaFold.qmd
          - text: "The Rashomon Quartet"
            href: content/Unit05_RashomonQuartet.qmd
      - text: "Wrap-Up, Conclusions, and Questions"
        href: content/wrap_up.qmd
      - section: "Supplemental Module"
        contents:
          - text: "BCR-ABL Fusion"
            href: content/Unit03_GeneticData.qmd
            
format:
  html:
    theme:
      light: cosmo
      dark: darkly
    css:
      - styles.css
    include-after-body: resources/theme-toggle-icon.html
    code-copy: true
    code-overflow: wrap
    toc: true
    toc-location: right

freeze: auto

editor: source
