services:
  ipd-workshop:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/thmccormick/ipd-short-course:latest
    container_name: ipd-workshop-rstudio
    ports:
      - "8787:8787"
    environment:
      PASSWORD: ${RSTUDIO_PASSWORD:-rstudio}
    restart: unless-stopped
